[ConnectionStrings]
SqlEngine = "MsSql"
PgSql = "Host=192.168.1.1:3306;Database=shana;Username=postgres;Password=XXXX"
MsSql = "Data Source=192.168.1.1,1433;Initial Catalog=master;User Id=sa; Password=XXXX;TrustServerCertificate=true"